-- Create EMPLOYEES Table
CREATE TABLE EMPLOYEES (
EMP_ID NUMBER PRIMARY KEY,
EMP_NAME VARCHAR2(100),
DEPT_ID NUMBER,
SALARY NUMBER,
COMMISSION NUMBER,
JOIN_DATE DATE,
MANAGER_ID NUMBER,
JOB_ROLE VARCHAR2(50)
);
-- Create DEPARTMENTS Table
CREATE TABLE DEPARTMENTS (
DEPT_ID NUMBER PRIMARY KEY,
DEPT_NAME VARCHAR2(100),
LOCATION VARCHAR2(100)
);
-- Create JOBS Table
CREATE TABLE JOBS (
JOB_ROLE VARCHAR2(50) PRIMARY KEY,
MIN_SALARY NUMBER,
MAX_SALARY NUMBER
);




