-- 11. Simulate MERGE from temp table into EMPLOYEES where EMP_ID = 17
MERGE INTO EMPLOYEES E
USING (SELECT * FROM EMPLOYEES WHERE EMP_ID = 17) TEMP
ON (E.EMP_ID = TEMP.EMP_ID)
WHEN MATCHED THEN
UPDATE SET E.SALARY = TEMP.SALARY
WHEN NOT MATCHED THEN
INSERT VALUES (TEMP.EMP_ID, TEMP.EMP_NAME, TEMP.DEPT_ID, TEMP.SALARY, TEMP.COMMISSION, TEMP.JOIN_DATE, TEMP.MANAGER_ID, TEMP.JOB_ROLE);
SELECT * FROM EMPLOYEES WHERE EMP_ID = 17;
