-- 14. Create a view and update
CREATE OR REPLACE VIEW HIGH_COMMISSION AS
SELECT * FROM EMPLOYEES
WHERE COMMISSION > 17;
UPDATE EMPLOYEES
SET SALARY = SALARY + 1000
WHERE EMP_ID IN (SELECT EMP_ID FROM HIGH_COMMISSION);

SELECT * FROM EMPLOYEES WHERE EMP_ID IN (SELECT EMP_ID FROM HIGH_COMMISSION);