-- 5. Employees and their managers where MANAGER_ID = 923
SELECT E.EMP_NAME AS EMPLOYEE, M.EMP_NAME AS MANAGER
FROM EMPLOYEES E
JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMP_ID
WHERE E.MANAGER_ID = 923;