-- 13. Create table with constraint MOD(value, 10) = 7
CREATE TABLE MOD10_CHECK (
VAL NUMBER,
CONSTRAINT MOD10_VAL CHECK (MOD(VAL, 10) = 7)
);
INSERT INTO MOD10_CHECK (VAL) VALUES (97);
SELECT * FROM MOD10_CHECK;
